// Package typeutil defines various enums and messages for conditions, events and logging purposes. It should stay
// backward-compatible because external systems (e.g. alerting systems) might rely upon those values.
package typeutil

const (
	// Condition types
	TypeReady = "Ready"

	// UpperCamelCase reasons enumerable, generic format is <Subject>[Verb]<Outcome (e.g. "Ready", "InProgress", "Failed"...)>
	RsnCreate               = "DatabaseReady"
	RsnDbCreateFail         = "DatabaseCreateFailed"
	RsnDbCreateInProg       = "DatabaseCreateInProgress"
	RsnDbCreateSucc         = "DatabaseCreateSuccess"
	RsnDbDeleteFail         = "DatabaseDeleteFailed"
	RsnDbDeleteInProg       = "DatabaseDeleteInProg"
	RsnDbGetFail            = "DatabaseGetFailed"
	RsnDbMetaParseFail      = "DatabaseMetaParseFailed"
	RsnDbOpQueueSucc        = "DatabaseQueueSuccess"
	RsnDbRotateFail         = "DatabaseRotateFail"
	RsnDbRotateInProg       = "DatabaseRotateInProgress"
	RsnDbRotateSucc         = "DatabaseRotateSuccess"
	RsnDbSpecParseFail      = "DatabaseSpecParseFailed"
	RsnDbUpdateFail         = "DatabaseUpdateFailed"
	RsnDbcConfigGetFail     = "DatabaseClassConfigGetFailed"
	RsnDbcGetFail           = "DatabaseClassGetFailed"
	RsnDbmsConfigGetFail    = "DbmsConfigGetFailed"
	RsnDbmsConnFail         = "DbmsConnectionFailed"
	RsnDbmsEndpointNotFound = "DbmsEndpointConnectFailed"
	RsnOpNotSupported       = "OperationNotSupported"
	RsnOpRenderFail         = "OperationRenderFailed"
	RsnReadyCondUpdateFail  = "ReadyConditionUpdateFailed"
	RsnSecretCreateFail     = "SecretCreateFailed"
	RsnSecretCreateSucc     = "SecretCreateSuccess"
	RsnSecretExists			= "RsnSecretExists"
	RsnSecretGetFail        = "SecretGetFailed"
	RsnSecretRenderFail     = "SecretRenderFailed"
	RsnSecretUpdateFail     = "SecretUpdateFailed"
	RsnSecretUpdateSucc     = "SecretUpdateSuccess"


	// Human-readable messages
	MsgDbCreateFail         = "could not create database instance on dbms endpoint"
	MsgDbCreateInProg       = "database instance is being provisioned on dbms endpoint"
	MsgDbCreateSucc         = "database instance provisioned successfully on dbms endpoint"
	MsgDbDeleteFail         = "could not delete database instance from dbms endpoint"
	MsgDbDeleteInProg       = "database instance is being deleted from dbms endpoint"
	MsgDbDeleted            = "database resource not found. Ignoring since object must be deleted"
	MsgDbGetFail            = "database resource get failed"
	MsgDbMetaParseFail      = "could not parse metadata field of database resource during operation values creation"
	MsgDbOpQueueSucc        = "database operation queued successfully"
	MsgDbRotateFail         = "database credentials rotation failed"
	MsgDbRotateInProg       = "database credentials rotation in progress"
	MsgDbRotateSucc         = "database credentials rotation completed"
	MsgDbSpecParseFail      = "could not parse spec field of database resource during operation values creation"
	MsgDbUpdateFail         = "could not update database resource, retrying"
	MsgDbcConfigGetFail     = "could not retrieve databaseclass name from dbms config"
	MsgDbcGetFail           = "databaseclass resource get failed"
	MsgDbmsConfigGetFail    = "could not retrieve dbms list from operator config"
	MsgDbmsConnFail         = "could not establish connection to dbms endpoint"
	MsgDbmsEndpointNotFound = "dbms connection not found in pool of connections"
	MsgOpNotSupported       = "operation is not supported for databaseclass"
	MsgOpRenderFail         = "could not render operation values"
	MsgReadyCondUpdateFail  = "could not update ready condition of resource"
	MsgSecretCreateFail     = "could not create secret resource for database resource"
	MsgSecretCreateSucc     = "secret created successfully"
	MsgSecretExists			= "secret exists already, please manually remove it from the cluster"
	MsgSecretGetFail        = "secret get failed"
	MsgSecretRenderFail     = "could not render secret data"
	MsgSecretUpdateFail     = "secret update failed"
	MsgSecretUpdateSucc     = "secret updated successfully"
	// Event types
	Normal  = "Normal"
	Warning = "Warning"
)
