replicaCount: 1

image:
  # -- Repository of the operator manager image.
  repository: basolur/kubernetes-dbaas
  pullPolicy: Always
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: "debug"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

# -- Allocating less resources might create problems
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 20Mi

nodeSelector: {}

tolerations: []

affinity: {}

# -- The termination grace period of your operator manager container.
terminationGracePeriodSeconds: 10

# -- Manager service account name
managerSaName: kubernetes-dbaas-controller-manager

# -- Should the ServiceAccount of the manager Pod automount the SA Account Token?
# otherwise
automountServiceAccountToken: true

# -- Arguments passed to the Operator binary, e.g. "--debug=true".
managerArgs: []

livenessProbe:
  httpGet:
    path: /healthz
    port: 8081
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /readyz
    port: 8081
  initialDelaySeconds: 5
  periodSeconds: 10

# -- If set to true, enabled the deployment of the RBAC needed to protect the /metrics endpoint.
enableMetricsRbac: false
# -- Namespaces of where Prometheus is deployed. It is required for discovering the ServiceMonitor used to scrape the metrics.
prometheusNamespace: prometheus
# -- Name of the Service Account allowed to scrape the metrics endpoint.
prometheusSaName: prometheus-kube-prometheus-prometheus
# -- Namespace of the Service Account allowed to scrape the metrics endpoint.
prometheusSaNamespace: prometheus

# -- DatabaseClass (dbc) generator (optional).
dbc:

# -- Endpoint Secrets generator (optional).
dbmsSecrets:

# -- Operator configuration including the relative Manager configuration.
# See https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.8.3/pkg/config/v1alpha1#ControllerManagerConfigurationSpec.
operatorConfig:
  health:
    healthProbeBindAddress: :8081
  metrics:
    bindAddress: 127.0.0.1:8080
  webhook:
    port: 9443
  leaderElection:
    leaderElect: true
    resourceName: bfa62c96.dbaas.bedag.ch
  # -- Specifies the maximum number of operations per second allowed per endpoint. Set to 0 to disable rate limiting.
  rps: 1
  # -- Describes the DBMS configuration. Each entry includes a "databaseClassName" attribute specifying
  # the name of the DatabaseClass resource associated with the endpoints along with an "endpoints" attribute
  # specifying the "name" of endpoint to be made available to end-users as well as its connection string (DSN).
  # To learn more about the supported DSN formats, see: https://github.com/xo/dburl.
  dbms:
    - databaseClassName: "databaseclass-sample-psql"
      endpoints:
        - name: "us-postgres-test"
          dsn: "postgres://postgres:Password&1@localhost:5432/postgres"
